AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BucketName:
    Type: String

Resources:
  NetworkStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://${BucketName}.s3.ap-southeast-1.amazonaws.com/SMPI/Resources/network-stack.yaml'
